### ISSUE TITLE
可以按_post下的第一级目录分类，但子目录不生成分类吗？

### ISSUE THREAD

**Issue by yehuohan** [xu-song/hexo-auto-category#2]
例如：

```
source/_post/web/framework/hexo.md
```
只生成web类，但不生成framework类吗？

我用的[这个主题](https://github.com/yelog/hexo-theme-3-hexo)，子目录也生成分类的话，主题中左侧栏的分类就太多了

**Comment by xu-song** [comment]
好想法。可以提供 `depth`这样的配置，比如

```yml
depth: 1
``` 
表示只生成一级目录。
实现很简单，对`slug.split`的结果处理一下。
稍等我加上。同时也欢迎PR

**Comment by yehuohan** [comment]
好的~~我先关闭issue了

**Comment by xu-song** [comment]
你可以运行一下

```
npm update
```

然后更改一下配置

```
# Generate categories from directory-tree
# Dependencies: https://github.com/xu-song/hexo-auto-category
# depth: the depth of directory-tree you want to generate, should > 0
auto_category:
 enable: true
 depth: 1
```
